### ISSUE TITLE
Unsound uninitialized array

### ISSUE THREAD

**Issue by shinmao** [rcore-os/rCore-Tutorial-v3-arm64#1]
Hi, I found some unsound use of `MaybeUninit` in the code.

https://github.com/rcore-os/rCore-Tutorial-v3-arm64/blob/ce03419fca121c18d0e949794795b6dfe990ca57/os/src/mm/uaccess.rs#L105

In this safe function, it would return an array of arbitrary types. `MaybeUninit::uninit()` could create an uninitialized `T` which is UB in Rust's type system. Here, the better use is to declare `buf` as `[<MaybeUninit>; N]`.

**Comment by equation314** [comment]
Got it, thanks!
